[package]
name = "potato_assistant"
version = "0.1.0"
edition = "2024"

[dependencies]
iced = "0.13.1"
dirs = "6.0.0"
dotenvy = "0.15.7"
envy = "0.4.2"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.8"
clap = { version = "4.5.53", features = ["derive"] }
